#' Gathering the whole texts as constants
#'
#' @description This file contains the whole text in the frontal application, saved for the whole project as constants
#'

v_Louvain <- HTML("The Louvain method is an algorithm to detect communities in large networks. It maximizes a modularity score for each community, where the modularity quantifies the quality of an assignment of nodes to communities. This means evaluating how much more densely connected the nodes within a community are, compared to how connected they would be in a random network.The Louvain algorithm is a hierarchical clustering algorithm, that recursively merges communities into a single node and executes the modularity clustering on the condensed graphs.")
v_Walktrap <- HTML("This algorithm was proposed by Pon & Latapy46. It is a hierarchical clustering algorithm. The basic idea of this method is that short distance random walks tend to stay in the same community. Starting from a totally non-clustered partition, the distances between all adjacent nodes are computed. Then, two adjacent communities are chosen, they are merged into a new one and the distances between communities are updated. This step is repeated (N-1) times, thus the computational complexity of this algorithm is O(EN^2). For sparse networks the computational complexity is O(N^2log(N)^40).")
v_Spinglass <- HTML("This algorithm was first proposed by Reichardt & Bornholdt. It is based on the Potts model. The basic principle of the method is that edges should connect nodes of the same spin state (community, in the current context), whereas nodes of different states (belonging to different communities) should be disconnected. Therefore, the aim of this algorithm is to find the ground state of a spin glass model with a Potts Hamiltonian. Simulated annealing has been used to minimise the system’s free energy. In a sparse graph, the computational complexity of this algorithm is approximately")
v_Leading_Eigen <- HTML("This algorithm was proposed by Newman39. The heart of this algorithm is the spectral optimisation of modularity by using the eigenvalues and eigenvectors of the modularity matrix. First, the leading eigenvector of the modularity matrix is calculated, and then the graph is split into two parts in a way that modularity improvement is maximised based on the leading eigenvector. After that, the modularity contribution is calculated at each step in the subdivision of a network. It stops once the value of the modularity contribution is not positive. Its computational complexity of each graph bipartition is O(N(E+N)), or O(N^2) on a sparse graph.")
v_Label_Propagation <- HTML("The Label Propagation algorithm (LPA) is a fast algorithm for finding communities in a graph. It detects these communities using network structure alone as its guide, and doesn’t require a pre-defined objective function or prior information about the communities. LPA works by propagating labels throughout the network and forming communities based on this process of label propagation. The intuition behind the algorithm is that a single label can quickly become dominant in a densely connected group of nodes, but will have trouble crossing a sparsely connected region. Labels will get trapped inside a densely connected group of nodes, and those nodes that end up with the same label when the algorithms finish can be considered part of the same community.")
v_Infomap <- HTML("This algorithm was proposed by Rosvall et al. It figures out communities by employing random walks to analyse the information flow through a network. This algorithm starts with encoding the network into modules in a way that maximises the amount of information about the original network. Then it sends the signal to a decoder through a channel with limited capacity. The decoder tries to decode the message and to construct a set of possible candidates for the original graph. The smaller the number of candidates, the more information about the original network has been transferred. This algorithm runs in O(E).")
v_Optimal <- HTML("Used under the constraint of the network size limitation, the goal of this algorithm is to optimize the modularity function itself, in order to find the corresponding clusters to the maximum modularity. The proposed implementation in R igraph library (Csrdi & Nepusz, 2006) is based on modularity optimization as a linear integer problem, initially introduced by Girvan and Newman (2002) (Girvan & Newman, 2002).")
v_Fast_Greedy <- HTML("the Fast greedy algorithm takes advantage of modularity optimization parameters, where every node in the network is considered as a single community, then merged to other communities according to its modularity. The process is applied to all nodes of the network and stops when modularity is not moving up.")

v_abstract <- helpText("Both Social Network Analysis (SNA) and Association Rules Learning (ARL) enriched our daily-lives through various applications, by improving axial roles in several domains. In particular, the community detection in online social networks (OSN) has interested researchers, for its valuable contribution in understanding systems complexity, as either for academic, commercial or further purposes. The aim of this paper is the identification of communities in OSN using knowledge extraction based on association rules methods. Furthermore, we propose a new ap- proach, namely ARL Clustering, using association rules learning for SNA. Particularly, we base our detection on user’s friendships of OSN by pro- cessing a four level technique to extract meaningful rules, converted later to communities. The conducted experimentation was applied on two syn- thetic real-world networks, and improved important results in identifying potential communities in comparison with existing approaches.")

v_title1 <- h3("A comprehensive literature review on community detection: Approaches and applications, the 10th International Conference on Ambiant Systems (ANT’19), Procedia Computer Science 151, pp-295-302, April 29 – May 2, 2019, Leuven, Belgium.")
v_paper1 <- helpText("Abstract Paper: Community detection has been designed as an axial field in Complex Network Analysis (CNA), since it allows to reveal cohesive and meaningful sub-graphs, recognize the features, functions, structure and dynamic of such complex networks. In this sense, various methods and approaches have been developed over the years to provide appropriate solutions to complex network paradigms, especially to community detection problems. Meanwhile, identifying communities in a given complex network is a big challenge for scientists, which needs a significant amount of literature and survey. In this paper, we detail literatures on community detection for complex networks, because of the need for researchers to perform reviews on the main papers related to identification of communities in complex networks, and in order to point out their principal strengths and limitations. We believe that this literature contribution can be a valuable source of information in particular for practitioners in the field of community detection, and do not include all existing contributions. Therefore, we have been interested in the value of the contribution of the selected approaches more than the chronological order of the publications.")

v_title2 <- h3("Community detection in Social Networks: A state of the art, The International Conference on Mathematics & Data Science (ICMDS’20), June 29-30, 2020. Khouribga, Morocco.")
v_paper2 <- helpText("Abstract Paper: Complex network analysis has become an evolutionary field, which attracts attention of researchers and practitioners from different scientific disciplines [1]. Actually, online social networks constitute one of this complex networks [2] that plays an important role in understanding human behaviors by studying online social interactions. In fact, to achieve this goal, community detection [3] has been introduced in various online social networking platforms as Facebook, Twitter, YouTube and so [4]. In this paper, we present a comprehensive literature on different approaches and methods proposed to deal with community detection issues. Therefore, the focus of this review is made on the value of the selected paper. We believe that this work does not include all published approaches and can be a valuable contribution for new researchers on community detection")

v_title3 <- h3("ARL Clustering method for community detection, applied to user’s friendship of Online Social Networks, The 7th International Conference on Multimedia Computing and Systems (ICMCS'20), October 1-3, 2020. Tetouan, Morocco.")
v_paper3 <- helpText("Video Conference ")

v_title4 <- h3("A novel approach of community detection using Association Rules Learning : Application to user’s friendships of Online Social Networks, The Fifth International Conference on Smart City Applications (SCA’20), October 7-9, 2020, Safranbolu, Turkey.")
v_paper4 <- helpText("Abstract Paper: Both Social Network Analysis (SNA) and Association Rules Learning (ARL) enriched our daily-lives through various applications, by improving axial roles in several domains. In particular, the community detection in online social networks (OSN) has interested researchers, for its valuable contribution in understanding systems complexity, as either for academic, commercial or further purposes. The aim of this paper is the identification of communities in OSN using knowledge extraction based on association rules methods. Furthermore, we propose a new approach, namely ARL Clustering, using association rules learning for SNA. Particularly, we base our detection on users’ friendship of OSN by processing a four level technique to extract meaningful rules, converted later to communities. The conducted experimentation was applied on two synthetic real-world networks, and improved important results in identifying potential communities in comparison with existing approaches.")
