name: ARLClustering

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps(dependencies = TRUE)

      - name: Check the package
        run: devtools::check()

      - name: Build the package
        run: devtools::build()

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ARLClustering_*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
